// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearApprovalHistory() {
  return window['go']['main']['App']['ClearApprovalHistory']();
}

export function ClearChatHistory() {
  return window['go']['main']['App']['ClearChatHistory']();
}

export function ExecuteShortcut(arg1) {
  return window['go']['main']['App']['ExecuteShortcut'](arg1);
}

export function GetApprovalHistory(arg1) {
  return window['go']['main']['App']['GetApprovalHistory'](arg1);
}

export function GetApprovalStats() {
  return window['go']['main']['App']['GetApprovalStats']();
}

export function GetChatHistory(arg1) {
  return window['go']['main']['App']['GetChatHistory'](arg1);
}

export function GetDesktopInfo() {
  return window['go']['main']['App']['GetDesktopInfo']();
}

export function GetKeyboardShortcuts() {
  return window['go']['main']['App']['GetKeyboardShortcuts']();
}

export function GetLogModules() {
  return window['go']['main']['App']['GetLogModules']();
}

export function GetLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLogs'](arg1, arg2, arg3);
}

export function GetPendingApprovals() {
  return window['go']['main']['App']['GetPendingApprovals']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSimulatedRequests() {
  return window['go']['main']['App']['GetSimulatedRequests']();
}

export function GetSystemStatus() {
  return window['go']['main']['App']['GetSystemStatus']();
}

export function GetThemeConfig() {
  return window['go']['main']['App']['GetThemeConfig']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetTheme(arg1, arg2) {
  return window['go']['main']['App']['SetTheme'](arg1, arg2);
}

export function ShowApproval(arg1) {
  return window['go']['main']['App']['ShowApproval'](arg1);
}

export function SimulateApproval(arg1) {
  return window['go']['main']['App']['SimulateApproval'](arg1);
}

export function StartBot() {
  return window['go']['main']['App']['StartBot']();
}

export function StopBot() {
  return window['go']['main']['App']['StopBot']();
}

export function SubmitApproval(arg1) {
  return window['go']['main']['App']['SubmitApproval'](arg1);
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['main']['App']['UpdateSetting'](arg1, arg2);
}
