package main

import (
	"fmt"
)

// PrintModelHelp 打印所有模型的详细说明
func PrintModelHelp() {
	fmt.Println("\n========================================")
	fmt.Println(" TestAIServer - 测试模型服务器")
	fmt.Println("========================================")
	fmt.Println("\n📋 可用模型列表:")
	fmt.Println()

	// testai-1.1
	fmt.Println("1. testai-1.1 - 快速响应模型")
	fmt.Println("   ├─ 延迟: 0 秒")
	fmt.Println("   ├─ 功能: 立即返回固定响应 \"好的，我知道了\"")
	fmt.Println("   └─ 用途: 测试基本的消息处理流程")
	fmt.Println()

	// testai-1.2
	fmt.Println("2. testai-1.2 - 中等延迟模型")
	fmt.Println("   ├─ 延迟: 30 秒")
	fmt.Println("   ├─ 功能: 延迟 30 秒后返回固定响应 \"好的，我知道了\"")
	fmt.Println("   └─ 用途: 测试中等延迟场景")
	fmt.Println()

	// testai-1.3
	fmt.Println("3. testai-1.3 - 长延迟模型")
	fmt.Println("   ├─ 延迟: 300 秒 (5 分钟)")
	fmt.Println("   ├─ 功能: 延迟 300 秒后返回固定响应 \"好的，我知道了\"")
	fmt.Println("   ├─ 用途: 测试长延迟场景、超时配置")
	fmt.Println("   └─ 场景: 模拟长时间 LLM 处理，测试 28/29/30 分钟超时配置")
	fmt.Println()

	// testai-2.0
	fmt.Println("4. testai-2.0 - 回显模型")
	fmt.Println("   ├─ 延迟: 0 秒")
	fmt.Println("   ├─ 功能: 原样返回用户发送的最后一条消息")
	fmt.Println("   └─ 用途: 测试消息传递是否正确")
	fmt.Println()

	// testai-3.0
	fmt.Println("5. testai-3.0 - 工具调用模型 ⭐")
	fmt.Println("   ├─ 延迟: 0 秒")
	fmt.Println("   ├─ 功能: 根据消息内容决定行为:")
	fmt.Println("   │")
	fmt.Println("   │  【场景 A: 检测到 PEER_CHAT 标记】")
	fmt.Println("   │  ├─ 触发条件: 消息包含 <PEER_CHAT>...</PEER_CHAT>")
	fmt.Println("   │  ├─ 返回: cluster_rpc 工具调用")
	fmt.Println("   │  └─ Agent 会执行工具，发送 peer_chat RPC")
	fmt.Println("   │")
	fmt.Println("   │  【场景 B: 普通消息】")
	fmt.Println("   │  ├─ 触发条件: 消息不包含 PEER_CHAT 标记")
	fmt.Println("   │  ├─ 返回: 原样返回用户消息")
	fmt.Println("   │  └─ 无工具调用")
	fmt.Println("   │")
	fmt.Println("   └─ 用途: 测试 peer_chat 工具调用、集群通信、长超时配置")
	fmt.Println()

	// testai-4.2
	fmt.Println("6. testai-4.2 - 客户端休眠模型（30秒）")
	fmt.Println("   ├─ 延迟: 0 秒")
	fmt.Println("   ├─ 功能: 调用客户端 sleep 工具")
	fmt.Println("   │")
	fmt.Println("   │  【第一轮】")
	fmt.Println("   │  └─ 返回: sleep 工具调用（30 秒）")
	fmt.Println("   │")
	fmt.Println("   │  【第二轮】")
	fmt.Println("   │  └─ 返回: \"工作完成\"")
	fmt.Println("   │")
	fmt.Println("   └─ 用途: 测试客户端工具调用、中等延迟")
	fmt.Println()

	// testai-4.3
	fmt.Println("7. testai-4.3 - 客户端休眠模型（300秒）⭐")
	fmt.Println("   ├─ 延迟: 0 秒")
	fmt.Println("   ├─ 功能: 调用客户端 sleep 工具")
	fmt.Println("   │")
	fmt.Println("   │  【第一轮】")
	fmt.Println("   │  └─ 返回: sleep 工具调用（300 秒 = 5 分钟）")
	fmt.Println("   │")
	fmt.Println("   │  【第二轮】")
	fmt.Println("   │  └─ 返回: \"工作完成\"")
	fmt.Println("   │")
	fmt.Println("   ├─ 用途: 测试客户端工具调用、长延迟、超时配置")
	fmt.Println("   └─ 场景: 模拟长时间客户端操作，测试 10 分钟 HTTP 超时配置")
	fmt.Println()

	fmt.Println("========================================")
	fmt.Println(" testai-3.0 详细使用说明")
	fmt.Println("========================================")
	fmt.Println()

	fmt.Println("📝 消息格式:")
	fmt.Println()
	fmt.Println("   要触发 peer_chat 工具调用，需要在消息中包含特殊标记:")
	fmt.Println()
	fmt.Println("   <PEER_CHAT>{JSON内容}</PEER_CHAT>")
	fmt.Println()

	fmt.Println("📦 JSON 结构:")
	fmt.Println()
	fmt.Println("   {")
	fmt.Println("     \"peer_id\": \"目标Agent的ID\",")
	fmt.Println("     \"content\": \"要发送给目标Agent的消息内容\"")
	fmt.Println("   }")
	fmt.Println()

	fmt.Println("💡 示例:")
	fmt.Println()
	fmt.Println("   示例 1 - 单行格式:")
	fmt.Println("   <PEER_CHAT>{\"peer_id\":\"agent-b\",\"content\":\"你好，我是 Agent A\"}</PEER_CHAT>")
	fmt.Println()
	fmt.Println("   示例 2 - 多行格式:")
	fmt.Println("   <PEER_CHAT>")
	fmt.Println("   {")
	fmt.Println("     \"peer_id\": \"agent-b\",")
	fmt.Println("     \"content\": \"这是一条测试消息\"")
	fmt.Println("   }")
	fmt.Println("   </PEER_CHAT>")
	fmt.Println()

	fmt.Println("🔧 工具调用流程:")
	fmt.Println()
	fmt.Println("   1. 用户发送消息给 Agent A (使用 testai-3.0)")
	fmt.Println("      消息包含: <PEER_CHAT>{\"peer_id\":\"agent-b\",\"content\":\"你好\"}</PEER_CHAT>")
	fmt.Println()
	fmt.Println("   2. Agent A 将消息发送给 testai-3.0")
	fmt.Println()
	fmt.Println("   3. testai-3.0 解析消息，返回工具调用:")
	fmt.Println("      {")
	fmt.Println("        \"tool_calls\": [{")
	fmt.Println("          \"id\": \"call-123\",")
	fmt.Println("          \"type\": \"function\",")
	fmt.Println("          \"function\": {")
	fmt.Println("            \"name\": \"cluster_rpc\",")
	fmt.Println("            \"arguments\": \"{\\\"peer_id\\\":\\\"agent-b\\\",\\\"action\\\":\\\"peer_chat\\\",...}\"")
	fmt.Println("          }")
	fmt.Println("        }]")
	fmt.Println("      }")
	fmt.Println()
	fmt.Println("   4. Agent A 执行 cluster_rpc 工具")
	fmt.Println()
	fmt.Println("   5. Agent B (使用 testai-1.3) 收到 peer_chat 请求")
	fmt.Println()
	fmt.Println("   6. Agent B 延迟 300 秒后返回响应")
	fmt.Println()
	fmt.Println("   7. Agent A 收到响应，返回给用户")
	fmt.Println()

	fmt.Println("========================================")
	fmt.Println(" 测试场景示例")
	fmt.Println("========================================")
	fmt.Println()

	fmt.Println("🧪 场景 1: 测试基本 peer_chat")
	fmt.Println()
	fmt.Println("   配置:")
	fmt.Println("   - Agent A: test/testai-3.0")
	fmt.Println("   - Agent B: test/testai-1.1 (快速响应)")
	fmt.Println()
	fmt.Println("   测试消息:")
	fmt.Println("   \"请给 agent-b 发送消息: <PEER_CHAT>{\\\"peer_id\\\":\\\"agent-b\\\",\\\"content\\\":\\\"测试消息\\\"}</PEER_CHAT>\"")
	fmt.Println()
	fmt.Println("   预期结果:")
	fmt.Println("   - Agent A 立即返回工具调用")
	fmt.Println("   - Agent B 立即处理并返回")
	fmt.Println("   - 总耗时: < 5 秒")
	fmt.Println()

	fmt.Println("🧪 场景 2: 测试长延迟 peer_chat (关键测试)")
	fmt.Println()
	fmt.Println("   配置:")
	fmt.Println("   - Agent A: test/testai-3.0")
	fmt.Println("   - Agent B: test/testai-1.3 (300秒延迟)")
	fmt.Println("   - 超时: RPC Client=30分钟, PeerChatHandler=29分钟, RPCChannel=28分钟")
	fmt.Println()
	fmt.Println("   测试消息:")
	fmt.Println("   \"请给 agent-b 发送消息: <PEER_CHAT>{\\\"peer_id\\\":\\\"agent-b\\\",\\\"content\\\":\\\"测试长延迟\\\"}</PEER_CHAT>\"")
	fmt.Println()
	fmt.Println("   预期结果:")
	fmt.Println("   - Agent A 立即发送 RPC")
	fmt.Println("   - Agent B 在 300 秒后返回")
	fmt.Println("   - Agent A 收到响应 (在超时范围内)")
	fmt.Println("   - 总耗时: ~300 秒 (5 分钟)")
	fmt.Println()
	fmt.Println("   验证点:")
	fmt.Println("   ✅ RPCChannel cleanup 不会提前关闭 channel")
	fmt.Println("   ✅ PeerChatHandler 的 29分钟超时不会触发")
	fmt.Println("   ✅ RPC Client 的 30分钟超时不会触发")
	fmt.Println("   ✅ 响应能正常返回")
	fmt.Println()

	fmt.Println("🧪 场景 3: 测试超时触发")
	fmt.Println()
	fmt.Println("   配置:")
	fmt.Println("   - Agent A: test/testai-3.0")
	fmt.Println("   - Agent B: test/testai-1.3 (300秒延迟)")
	fmt.Println("   - 修改 PeerChatHandler 超时为 60秒 (模拟)")
	fmt.Println()
	fmt.Println("   预期结果:")
	fmt.Println("   - Agent B 在 60秒时超时")
	fmt.Println("   - Agent A 收到 timeout 错误")
	fmt.Println("   - 总耗时: ~60 秒")
	fmt.Println()

	fmt.Println("🧪 场景 4: 测试客户端 sleep 工具（30秒）")
	fmt.Println()
	fmt.Println("   配置:")
	fmt.Println("   - Agent: test/testai-4.2")
	fmt.Println("   - 客户端: sleep 工具（30秒）")
	fmt.Println()
	fmt.Println("   测试消息:")
	fmt.Println("   \"执行一个 30 秒的任务\"")
	fmt.Println()
	fmt.Println("   预期流程:")
	fmt.Println("   1. Agent 发送消息给 testai-4.2")
	fmt.Println("   2. testai-4.2 返回 sleep 工具调用（30 秒）")
	fmt.Println("   3. Agent 执行 sleep 工具，等待 30 秒")
	fmt.Println("   4. sleep 工具返回 \"Slept for 30 seconds\"")
	fmt.Println("   5. testai-4.2 返回 \"工作完成\"")
	fmt.Println()
	fmt.Println("   预期结果:")
	fmt.Println("   - 总耗时: ~30 秒")
	fmt.Println("   - 返回: \"工作完成\"")
	fmt.Println()

	fmt.Println("🧪 场景 5: 测试客户端 sleep 工具（300秒）- 关键测试 ⭐")
	fmt.Println()
	fmt.Println("   配置:")
	fmt.Println("   - Agent: test/testai-4.3")
	fmt.Println("   - 客户端: sleep 工具（300秒）")
	fmt.Println("   - HTTP 超时: 10 分钟")
	fmt.Println()
	fmt.Println("   测试消息:")
	fmt.Println("   \"执行一个 5 分钟的任务\"")
	fmt.Println()
	fmt.Println("   预期流程:")
	fmt.Println("   1. Agent 发送消息给 testai-4.3")
	fmt.Println("   2. testai-4.3 返回 sleep 工具调用（300 秒）")
	fmt.Println("   3. Agent 执行 sleep 工具，等待 300 秒")
	fmt.Println("   4. sleep 工具返回 \"Slept for 300 seconds\"")
	fmt.Println("   5. testai-4.3 返回 \"工作完成\"")
	fmt.Println()
	fmt.Println("   预期结果:")
	fmt.Println("   - 总耗时: ~300 秒 (5 分钟)")
	fmt.Println("   - 返回: \"工作完成\"")
	fmt.Println()
	fmt.Println("   验证点:")
	fmt.Println("   ✅ HTTP 客户端 10 分钟超时足够等待 5 分钟的 sleep")
	fmt.Println("   ✅ sleep 工具支持 context 取消（可中断）")
	fmt.Println("   ✅ 客户端工具调用流程正常")
	fmt.Println()

	fmt.Println("🧪 场景 6: 测试组合场景 - peer_chat + 客户端 sleep")
	fmt.Println()
	fmt.Println("   配置:")
	fmt.Println("   - Agent A: test/testai-3.0 (peer_chat)")
	fmt.Println("   - Agent B: test/testai-4.3 (客户端 sleep)")
	fmt.Println()
	fmt.Println("   测试消息:")
	fmt.Println("   \"请给 agent-b 发送消息: <PEER_CHAT>{\"peer_id\":\"agent-b\",\"content\":\"执行任务\"}</PEER_CHAT>\"")
	fmt.Println()
	fmt.Println("   预期流程:")
	fmt.Println("   1. Agent A 收到消息，调用 testai-3.0")
	fmt.Println("   2. testai-3.0 返回 cluster_rpc 工具调用")
	fmt.Println("   3. Agent A 执行 cluster_rpc，发送 peer_chat 给 Agent B")
	fmt.Println("   4. Agent B 收到 peer_chat 请求，调用 testai-4.3")
	fmt.Println("   5. testai-4.3 返回 sleep 工具调用（300 秒）")
	fmt.Println("   6. Agent B 执行 sleep 工具，等待 300 秒")
	fmt.Println("   7. testai-4.3 返回 \"工作完成\"")
	fmt.Println("   8. Agent B 返回响应给 Agent A")
	fmt.Println("   9. Agent A 返回响应给用户")
	fmt.Println()
	fmt.Println("   预期结果:")
	fmt.Println("   - 总耗时: ~300 秒 (5 分钟)")
	fmt.Println("   - 返回: \"工作完成\"")
	fmt.Println()

	fmt.Println("========================================")
	fmt.Println(" NemesisBot 配置示例")
	fmt.Println("========================================")
	fmt.Println()

	fmt.Println("📝 配置 Agent A (使用 testai-3.0):")
	fmt.Println()
	fmt.Println("   # 添加模型")
	fmt.Println("   nemesisbot model add \\")
	fmt.Println("     --model test/testai-3.0 \\")
	fmt.Println("     --base http://127.0.0.1:8080/v1 \\")
	fmt.Println("     --key test-key \\")
	fmt.Println("     --default")
	fmt.Println()
	fmt.Println("   # 配置集群")
	fmt.Println("   nemesisbot cluster init --name \"Agent-A\" --role worker")
	fmt.Println("   nemesisbot cluster enable")
	fmt.Println()

	fmt.Println("📝 配置 Agent B (使用 testai-1.3):")
	fmt.Println()
	fmt.Println("   # 添加模型")
	fmt.Println("   nemesisbot model add \\")
	fmt.Println("     --model test/testai-1.3 \\")
	fmt.Println("     --base http://127.0.0.1:8080/v1 \\")
	fmt.Println("     --key test-key \\")
	fmt.Println("     --default")
	fmt.Println()
	fmt.Println("   # 配置集群")
	fmt.Println("   nemesisbot cluster init --name \"Agent-B\" --role worker")
	fmt.Println("   nemesisbot cluster enable")
	fmt.Println()

	fmt.Println("========================================")
	fmt.Println(" 启动服务器")
	fmt.Println("========================================")
	fmt.Println()
	fmt.Println("   1. 启动 TestAIServer:")
	fmt.Println("      ./testaiserver.exe")
	fmt.Println()
	fmt.Println("   2. 启动 Agent A:")
	fmt.Println("      nemesisbot gateway")
	fmt.Println()
	fmt.Println("   3. 启动 Agent B (另一个终端):")
	fmt.Println("      nemesisbot gateway --workspace /path/to/agent-b")
	fmt.Println()
	fmt.Println("   4. 发送测试消息:")
	fmt.Println("      通过 Web UI 或 API 发送包含 <PEER_CHAT> 标记的消息")
	fmt.Println()

	fmt.Println("========================================")
	fmt.Println(" API 端点")
	fmt.Println("========================================")
	fmt.Println()
	fmt.Println("   GET  /v1/models           - 列出所有可用模型")
	fmt.Println("   POST /v1/chat/completions - 聊天补全接口")
	fmt.Println()
	fmt.Println("   OpenAI 兼容格式，支持流式和非流式响应")
	fmt.Println()

	fmt.Println("========================================")
	fmt.Println(" 日志位置")
	fmt.Println("========================================")
	fmt.Println()
	fmt.Println("   TestAIServer 日志: ./log/")
	fmt.Println("   NemesisBot 日志: ~/.nemesisbot/logs/")
	fmt.Println()

	fmt.Println("========================================")
	fmt.Println()
}
