// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDemoRequests():Promise<Array<main.ApprovalRequest>>;

export function GetSystemInfo():Promise<Record<string, any>>;

export function SimulateBackendRequest(arg1:string):Promise<main.ApprovalRequest>;

export function SubmitApproval(arg1:main.ApprovalResponse):Promise<void>;
