// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDemoRequests() {
  return window['go']['main']['App']['GetDemoRequests']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function SimulateBackendRequest(arg1) {
  return window['go']['main']['App']['SimulateBackendRequest'](arg1);
}

export function SubmitApproval(arg1) {
  return window['go']['main']['App']['SubmitApproval'](arg1);
}
