// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearApprovalHistory():Promise<void>;

export function ClearChatHistory():Promise<void>;

export function ExecuteShortcut(arg1:string):Promise<void>;

export function GetApprovalHistory(arg1:number):Promise<Array<main.ApprovalHistoryItem>>;

export function GetApprovalStats():Promise<main.ApprovalStats>;

export function GetChatHistory(arg1:number):Promise<Array<main.ChatMessage>>;

export function GetDesktopInfo():Promise<main.DesktopInfo>;

export function GetKeyboardShortcuts():Promise<Array<main.KeyboardShortcut>>;

export function GetLogModules():Promise<Array<string>>;

export function GetLogs(arg1:string,arg2:string,arg3:number):Promise<Array<main.LogEntry>>;

export function GetPendingApprovals():Promise<Array<main.ApprovalRequest>>;

export function GetSettings():Promise<Array<main.Setting>>;

export function GetSimulatedRequests():Promise<Array<main.SimulatedRequest>>;

export function GetSystemStatus():Promise<main.SystemStatus>;

export function GetThemeConfig():Promise<main.ThemeConfig>;

export function SendMessage(arg1:string):Promise<string>;

export function SetTheme(arg1:string,arg2:boolean):Promise<void>;

export function ShowApproval(arg1:main.ApprovalRequest):Promise<main.ApprovalResponse>;

export function SimulateApproval(arg1:string):Promise<void>;

export function StartBot():Promise<void>;

export function StopBot():Promise<void>;

export function SubmitApproval(arg1:main.ApprovalResponse):Promise<void>;

export function UpdateSetting(arg1:string,arg2:string):Promise<void>;
